engines:
  golint:
    enabled: false
  gofmt:
    enabled: false
  govet:
    enabled: false
  # Might be moved out with #24. Disabling for now
  eslint:
    enabled: false
  csslint:
    enabled: false
