engines:
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  # Might be moved out with #24. Disabling for now
  eslint:
    enabled: false
  csslint:
    enabled: false
exclude_paths:
  - "**.pb.go"
