version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.1
    working_directory: /go/src/github.com/pp2p/paranoid
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: Install FUSE
          command: apt update && apt install -y fuse
      - run:
          name: Get Go dependencies
          command: go get -v ./...
      - run:
          name: install go junit
          command: go get -u github.com/jstemmer/go-junit-report
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Test
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v ./... | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results
